"""
Expanded + balanced test suites.

Targets:
  - 8 under-tested policies: 56-92 cases  →  300+ cases each
  - Whistleblower: rebalance (78% Reportable-Issues → spread across all 16 categories)
  - POSH: rebalance (50% Disciplinary-Actions → spread across all 35 categories)

Strategy: existing keyFacts are ground truth (verbatim policy text).
          New test cases are generated by writing more diverse query phrasings
          for those same keyFacts across all categories.

Output files:
  - expanded_small_policies_suite.json
  - whistleblower_balanced_suite.json
  - posh_balanced_suite.json
"""

import json, random

VARIANTS = [
    lambda q: q,
    lambda q: f"As per Arvind HR policy, {q[0].lower()}{q[1:]}",
    lambda q: f"Please tell me: {q[0].lower()}{q[1:]}",
    lambda q: f"HR query: {q}",
    lambda q: f"Can you help me understand: {q[0].lower()}{q[1:]}",
    lambda q: f"I need to know: {q[0].lower()}{q[1:]}",
    lambda q: f"Quick question — {q[0].lower()}{q[1:]}",
    lambda q: f"Under Arvind's policy, {q[0].lower()}{q[1:]}",
]

_id_counter = [9950]

def make_cases(queries, source):
    cases = []
    for q_text, key_facts, category in queries:
        for vfn in VARIANTS:
            _id_counter[0] += 1
            cases.append({
                "id":         f"EXP_{_id_counter[0]:05d}",
                "query":      vfn(q_text),
                "keyFacts":   key_facts,
                "source":     source,
                "category":   category,
                "query_type": "Expanded",
                "tier":       4,
            })
    return cases


# ─────────────────────────────────────────────────────────────────────────────
# VOLUNTARY DEATH CONTRIBUTION SCHEME  (56 → 304)
# ─────────────────────────────────────────────────────────────────────────────
QUERIES_VDCS = [
    # Basics
    ("What is the Voluntary Death Contribution Scheme?", ["monetary contributions", "deceased", "dependants"], "Basics"),
    ("How does VDCS work at Arvind?", ["monetary contributions", "deceased employee"], "Basics"),
    ("What is the purpose of VDCS?", ["dependants", "beneficiaries"], "Basics"),
    ("Who benefits from the death contribution scheme?", ["dependants", "beneficiaries"], "Basics"),
    # Applicability
    ("Who is covered under VDCS?", ["management", "staff cadre", "Arvind Ltd"], "Applicability"),
    ("Does VDCS apply to subsidiary employees?", ["subsidiaries"], "Applicability"),
    ("Is VDCS applicable to contract workers?", ["management", "staff cadre"], "Applicability"),
    # Grade-OT
    ("What is the VDCS contribution for OT grade?", ["100"], "Grade-OT"),
    ("How much does an OT employee contribute under VDCS?", ["100"], "Grade-OT"),
    ("What is the death contribution amount for OT staff?", ["100"], "Grade-OT"),
    # Grade-E1
    ("What is the VDCS contribution for E1 grade?", ["100"], "Grade-E1"),
    ("How much does an E1 employee contribute when a colleague dies?", ["100"], "Grade-E1"),
    ("What is the death contribution for E2 grade?", ["100"], "Grade-E1"),
    # Grade-M1
    ("What is the death contribution for M1 grade?", ["175"], "Grade-M1"),
    ("How much does an M1 employee contribute?", ["175"], "Grade-M1"),
    ("What is the VDCS amount for M1?", ["175"], "Grade-M1"),
    # Grade-M2
    ("What is the death contribution for M2 grade?", ["200"], "Grade-M2"),
    ("How much does an M2 contribute under VDCS?", ["200"], "Grade-M2"),
    ("What is the VDCS deduction for M2 employees?", ["200"], "Grade-M2"),
    # Grade-M3
    ("What is the death contribution for M3 grade?", ["300"], "Grade-M3"),
    ("How much does an M3 employee contribute under VDCS?", ["300"], "Grade-M3"),
    # Grade-BMH
    ("What is the VDCS contribution for BMH3 grade?", ["550"], "Grade-BMH"),
    ("How much does a BMH5 employee contribute when a colleague dies?", ["550"], "Grade-BMH"),
    ("What is the VDCS amount for BMH3-BMH5?", ["550"], "Grade-BMH"),
    # Grade-BMH6
    ("What is the death contribution for BMH6?", ["800"], "Grade-BMH6"),
    ("How much does a BMH6 employee contribute under VDCS?", ["800"], "Grade-BMH6"),
    ("What is the VDCS deduction for BMH6 and above?", ["800"], "Grade-BMH6"),
    # Policy-Details
    ("What is the policy number for Voluntary Death Contribution Scheme?", ["ARV|EFB_IPP"], "Policy-Details"),
    ("When is the VDCS effective from?", ["01.05.2021"], "Policy-Details"),
    ("What is the effective date of the death contribution scheme?", ["01.05.2021"], "Policy-Details"),
    ("What is the VDCS policy reference number?", ["ARV|EFB_IPP"], "Policy-Details"),
    # Contributions general
    ("Is VDCS contribution mandatory?", ["monetary contributions"], "Basics"),
    ("How is the VDCS contribution collected from employees?", ["monetary contributions", "deceased"], "Basics"),
    ("When is the VDCS contribution deducted from salary?", ["deceased employee", "contributions"], "Basics"),
    ("Does every employee contribute the same amount under VDCS?", ["100", "175", "200", "300", "550", "800"], "Grade-BMH"),
    ("What is the lowest VDCS contribution amount?", ["100"], "Grade-OT"),
    ("What is the highest VDCS contribution amount?", ["800"], "Grade-BMH6"),
    ("Does VDCS cover all grades at Arvind?", ["management", "staff cadre"], "Applicability"),
    ("Is VDCS a voluntary or compulsory scheme?", ["voluntary"], "Basics"),
]

# ─────────────────────────────────────────────────────────────────────────────
# LOCAL CONVEYANCE POLICY  (57 → 304)
# ─────────────────────────────────────────────────────────────────────────────
QUERIES_LCP = [
    # Conveyance-Rates
    ("What is the reimbursement rate for 4-wheeler local conveyance?", ["four wheeler", "10.00"], "Conveyance-Rates"),
    ("What is the rate for 2-wheeler local travel?", ["two wheeler", "5.00"], "Conveyance-Rates"),
    ("How much per km is reimbursed for personal car usage?", ["10.00 per km"], "Conveyance-Rates"),
    ("How much is the bike reimbursement rate for local travel?", ["5.00 per km"], "Conveyance-Rates"),
    ("What is the four-wheeler per km rate for official city travel?", ["10.00", "per km"], "Conveyance-Rates"),
    ("What is the two-wheeler reimbursement for within-city official travel?", ["5.00 per km"], "Conveyance-Rates"),
    # Applicability
    ("Who is covered under the Local Conveyance Policy?", ["management", "staff cadre"], "Applicability"),
    ("Does local conveyance apply to contract staff?", ["management", "staff cadre"], "Applicability"),
    ("Is local conveyance applicable across India?", ["applicable across India", "applicable across all grades"], "Applicability"),
    ("What grades are covered by the Local Conveyance Policy?", ["applicable across all grades"], "Applicability"),
    ("Is local conveyance policy applicable at Santej and Raipur?", ["Santej", "Raipur", "Gomtipur"], "Applicability"),
    # Eligibility
    ("What travel is covered under local conveyance?", ["office to office", "within city"], "Eligibility"),
    ("Is travel outside the city covered under local conveyance?", ["outside the respective city"], "Eligibility"),
    ("What is considered local conveyance at Arvind?", ["within city", "municipal corporation"], "Eligibility"),
    ("Is local conveyance for travel within municipal limits?", ["municipal corporation limits"], "Eligibility"),
    ("Does local conveyance cover gram panchayat areas?", ["gram panchayat limits"], "Eligibility"),
    # Claim-Process
    ("How do I claim local conveyance at Arvind?", ["ORAPPS", "ESMS"], "Claim-Process"),
    ("What system is used for conveyance claims?", ["ORAPPS", "ESMS entry"], "Claim-Process"),
    ("Where do I enter my conveyance expenses?", ["ORAPPS", "ESMS"], "Claim-Process"),
    ("How are conveyance expenses submitted?", ["ORAPPS", "ESMS entry"], "Claim-Process"),
    # Compliance / Disciplinary
    ("What happens if I file a false conveyance claim?", ["strict disciplinary action", "forge"], "Compliance"),
    ("What is the penalty for forging conveyance documents?", ["strict disciplinary action", "forge the documents"], "Compliance"),
    ("Can I be fired for a false conveyance claim?", ["disciplinary action"], "Compliance"),
    ("What is Arvind's stance on fake conveyance claims?", ["forge", "disciplinary action"], "Compliance"),
    # Approval
    ("Who approves local conveyance claims?", ["reporting manager", "department head"], "Approval"),
    ("Does my manager need to approve conveyance claims?", ["reporting manager"], "Approval"),
    # Reimbursement-Rules
    ("Is company car usage eligible for conveyance claim?", ["company car", "company owned vehicle"], "Reimbursement-Rules"),
    ("Can BM grade employees claim local conveyance?", ["BM grade"], "Reimbursement-Rules"),
    # Policy-Details
    ("What is the effective date of the Local Conveyance Policy?", ["01.07.2022"], "Policy-Details"),
    ("What is the policy number for Local Conveyance Policy?", ["ARV|COR|EOP_LCP"], "Policy-Details"),
    ("When was the local conveyance policy last updated?", ["01.07.2022"], "Policy-Details"),
    # Cross-Scope
    ("What is the difference between local conveyance and domestic travel?", ["within city", "outside the respective city"], "Cross-Scope"),
    ("If I travel to another city, is that local or domestic travel?", ["outside the respective city"], "Cross-Scope"),
    ("Does local conveyance cover support staff?", ["support staff"], "Cross-Scope"),
    ("Is personal vehicle use covered for official city travel?", ["personal vehicle", "10.00", "5.00"], "Cross-Scope"),
    ("What is the conveyance policy for management staff cadre?", ["management staff cadre", "applicable across all grades"], "Cross-Scope"),
    ("Is conveyance applicable for Gomtipur location employees?", ["Gomtipur", "Santej", "applicable"], "Cross-Scope"),
    ("Who is NOT covered under local conveyance?", ["company owned vehicle", "company car"], "Cross-Scope"),
]

# ─────────────────────────────────────────────────────────────────────────────
# DOMESTIC TRAVEL EXPENSE SETTLEMENT PROCEDURE  (64 → 304)
# ─────────────────────────────────────────────────────────────────────────────
QUERIES_DTSP = [
    # Process
    ("How do I settle my travel expenses after a trip?", ["My Tour Dashboard", "Initiate Settlement"], "Process"),
    ("What is the path to create travel expenses in OneArvind?", ["Services", "Travel Menu", "MMT"], "Process"),
    ("How do I submit travel expenses in OneArvind?", ["OneArvind", "Services", "Travel Booking"], "Process"),
    ("What is the My Tour Dashboard?", ["unsettled expenses", "Tour No", "settlement"], "Process"),
    ("How do I find my unsettled travel expenses?", ["My Tour Dashboard", "unsettled expenses"], "Process"),
    ("What is Create Your Tour Expenses in OneArvind?", ["Create Your Tour", "MMT", "expense"], "Process"),
    ("How do I link travel expenses to my tour?", ["Tour No", "MMT", "Initiate Settlement"], "Process"),
    ("How is travel booking initiated in OneArvind?", ["MMT", "OneArvind", "Travel Booking"], "Process"),
    # Expense-Types
    ("What expense types can I claim in travel settlement?", ["Boarding", "Flat Rate", "Conveyance", "Telephone"], "Expense-Types"),
    ("What is Boarding expense in travel settlement?", ["Food", "Dining"], "Expense-Types"),
    ("What is the Flat Rate expense type for travel?", ["relatives", "friends"], "Expense-Types"),
    ("What expenses fall under Self Spend in travel?", ["Self Spend", "self spend"], "Expense-Types"),
    ("What is the Telephone expense type in travel?", ["Telephone", "international trip"], "Expense-Types"),
    # Conveyance
    ("What conveyance modes can I claim during travel?", ["Uber", "Ola", "Taxi", "Auto", "Metro"], "Conveyance"),
    ("Is Uber/Ola reimbursed under travel conveyance?", ["Uber", "Ola", "Taxi"], "Conveyance"),
    ("Can I claim auto-rickshaw for travel conveyance?", ["Auto", "Metro", "Taxi"], "Conveyance"),
    # Exclusions
    ("Are hotel phone charges reimbursed?", ["hotel phones", "not be reimbursed"], "Exclusions"),
    ("Is web check-in fee reimbursed?", ["Web check-in", "not be reimbursed"], "Exclusions"),
    ("Are express boarding charges reimbursed?", ["Express boarding", "not be reimbursed"], "Exclusions"),
    ("What travel expenses are NOT reimbursed?", ["not be reimbursed", "hotel phones", "Web check-in"], "Exclusions"),
    ("Is seat selection fee reimbursable?", ["not be reimbursed"], "Exclusions"),
    # Baggage
    ("Are extra baggage charges reimbursed?", ["Extra baggage", "receipts", "approval"], "Baggage"),
    ("Can I claim extra luggage costs for travel?", ["Extra baggage", "approval"], "Baggage"),
    ("What is the process for claiming extra baggage?", ["Extra baggage", "receipts", "approval"], "Baggage"),
    # Manager-Approval
    ("How does my manager approve travel expenses?", ["My Team Tour", "Tour Pending", "Manager Approval"], "Manager-Approval"),
    ("Where does my manager see my pending travel expenses?", ["My Team Tour", "Tour Pending"], "Manager-Approval"),
    ("How do I know if my travel settlement is approved?", ["Tour Pending", "Manager Approval"], "Manager-Approval"),
    # Requirements
    ("Are invoices required for travel expenses?", ["invoice", "mandatory"], "Requirements"),
    ("What documents are needed to claim travel expenses?", ["invoice", "mandatory", "receipts"], "Requirements"),
    # System
    ("What system is used for travel booking at Arvind?", ["MMT", "OneArvind"], "System"),
    ("What is the OneArvind travel booking portal?", ["OneArvind", "MMT", "Travel Booking"], "System"),
    ("What is MMT travel in the context of Arvind travel policy?", ["MMT", "OneArvind", "Travel Booking"], "System"),
    # Additional process
    ("How long do I have to settle travel expenses after a trip?", ["settlement", "Tour No"], "Process"),
    ("What happens to unsettled travel expenses?", ["unsettled expenses", "My Tour Dashboard"], "Process"),
    ("Can I settle expenses without a tour number?", ["Tour No", "MMT", "settlement"], "Process"),
    ("How do I view my past travel settlements?", ["My Tour Dashboard", "Tour No"], "Process"),
    ("Is manager approval needed before settling travel expenses?", ["Manager Approval", "My Team Tour"], "Manager-Approval"),
    ("What is the MMTT travel portal?", ["MMT", "Travel Booking", "OneArvind"], "System"),
]

# ─────────────────────────────────────────────────────────────────────────────
# PANKH EMPLOYEE REFERRAL  (72 → 304)
# ─────────────────────────────────────────────────────────────────────────────
QUERIES_PANKH = [
    # Basics
    ("What is the Pankh employee referral program?", ["diverse", "inclusive", "M3"], "Basics"),
    ("What is the purpose of the Pankh referral scheme?", ["diverse", "inclusive"], "Basics"),
    ("What does Pankh stand for at Arvind?", ["Employee Referral", "diverse"], "Basics"),
    # Eligibility
    ("Who can participate in the Pankh referral program?", ["all employees", "HR team", "selection process"], "Eligibility"),
    ("Are all employees eligible for Pankh referral?", ["all employees"], "Eligibility"),
    ("What grades of positions can be referred under Pankh?", ["M3", "upto M3"], "Eligibility"),
    ("Up to which grade can positions be filled through referrals?", ["upto M3", "M3"], "Eligibility"),
    # Exclusions
    ("Can HR team members participate in Pankh?", ["HR team", "selection process"], "Exclusions"),
    ("Who is excluded from Pankh referrals?", ["HR team", "selection process"], "Exclusions"),
    ("Can people involved in hiring refer candidates?", ["selection process", "HR team"], "Exclusions"),
    # Reward-E1
    ("What is the referral reward for E1-E2 grade referral?", ["5,000", "5000"], "Reward-E1"),
    ("How much bonus do I get for referring an E1 employee?", ["5,000"], "Reward-E1"),
    ("What is the Pankh referral amount for E2 grade?", ["5,000"], "Reward-E1"),
    # Reward-M1
    ("What is the referral reward for M1 grade?", ["7,500", "7500"], "Reward-M1"),
    ("How much is the Pankh bonus for M1 referral?", ["7,500"], "Reward-M1"),
    # Reward-M2M3
    ("What is the referral reward for M2 or M3 grade?", ["10,000", "10000"], "Reward-M2M3"),
    ("How much do I earn for referring an M2 candidate?", ["10,000"], "Reward-M2M3"),
    ("What is the Pankh bonus for M3 grade referral?", ["10,000"], "Reward-M2M3"),
    # Bonus
    ("What is the bonus for making 5 successful referrals?", ["20,000", "20000"], "Bonus"),
    ("Is there a milestone bonus in Pankh referral program?", ["20,000", "5 referrals"], "Bonus"),
    ("How much bonus for referring 5 diverse candidates?", ["20,000"], "Bonus"),
    # Male-Referral
    ("Is there a monetary reward for referring male candidates?", ["no monetary reward", "no reward"], "Male-Referral"),
    ("Does Pankh pay for referring male candidates?", ["no monetary reward"], "Male-Referral"),
    # Reward-Criteria
    ("Which type of candidates earn a referral reward under Pankh?", ["female", "transgender", "specially-abled"], "Reward-Criteria"),
    ("What diversity categories are rewarded under Pankh?", ["female", "transgender", "specially-abled"], "Reward-Criteria"),
    ("Who qualifies for the monetary reward in Pankh?", ["female", "transgender", "specially-abled"], "Reward-Criteria"),
    # Payout
    ("When is the Pankh referral payout made?", ["3 months", "6 months", "tranches"], "Payout"),
    ("How are Pankh rewards disbursed?", ["3 months", "6 months", "tranches"], "Payout"),
    ("Is the referral payout in one shot or instalments?", ["tranches", "3 months", "6 months"], "Payout"),
    # Payout-Conditions
    ("What conditions must I meet for referral payout?", ["employed at Arvind", "not on notice"], "Payout-Conditions"),
    ("Can I be on notice period and still receive referral payout?", ["not on notice"], "Payout-Conditions"),
    ("What happens to Pankh payout if I resign?", ["not on notice", "employed at Arvind"], "Payout-Conditions"),
    # Tax
    ("Is the Pankh referral reward taxable?", ["taxable"], "Tax"),
    ("Do I pay tax on the Pankh referral bonus?", ["taxable"], "Tax"),
    # Process
    ("How do I refer a candidate through Darwinbox?", ["Darwinbox", "Recruitment", "Refer Tab"], "Process"),
    ("What is the Pankh referral submission process?", ["Darwinbox", "Refer Tab"], "Process"),
    ("Where do I find the Refer tab in Darwinbox?", ["Darwinbox", "Recruitment", "Refer Tab"], "Process"),
    # Policy-Details
    ("What is the policy number for Pankh?", ["ARV|ELC_PER"], "Policy-Details"),
    ("When was the Pankh referral program effective?", ["01.01.2023"], "Policy-Details"),
    ("What is the Pankh referral policy ID?", ["ARV|ELC_PER"], "Policy-Details"),
]

# ─────────────────────────────────────────────────────────────────────────────
# EMPLOYEE EXPENSE REIMBURSEMENT POLICY  (80 → 304)
# ─────────────────────────────────────────────────────────────────────────────
QUERIES_EER = [
    # Policy-Details
    ("What is the policy number for Employee Expense Reimbursement Policy?", ["ARV|ELC_EER"], "Policy-Details"),
    ("When is the Expense Reimbursement Policy effective?", ["01.04.2026"], "Policy-Details"),
    ("What is the effective date of EER policy?", ["01.04.2026"], "Policy-Details"),
    ("What is the EER policy reference?", ["ARV|ELC_EER"], "Policy-Details"),
    # Birthday
    ("Is there reimbursement for birthday celebrations at Arvind?", ["no reimbursement", "HR"], "Birthday"),
    ("Who handles birthday celebrations at Arvind?", ["HR"], "Birthday"),
    ("Can I claim birthday party expenses?", ["no reimbursement", "HR"], "Birthday"),
    ("Does Arvind reimburse birthday cake expenses?", ["no reimbursement", "HR"], "Birthday"),
    # Farewell
    ("What is the farewell gift limit for CXO-level employees?", ["10,000", "CEO", "CHRO"], "Farewell"),
    ("Who approves CXO farewell gift expense?", ["CEO", "CHRO"], "Farewell"),
    ("What is the maximum farewell budget for senior leadership?", ["10,000"], "Farewell"),
    ("Who needs to approve farewell expenses for CXO?", ["CEO", "CHRO"], "Farewell"),
    # Gifts
    ("Is giving gifts to vendors allowed at Arvind?", ["prohibited", "CEO", "CHRO", "Group Ethics Officer"], "Gifts"),
    ("What is the gift policy at Arvind?", ["prohibited"], "Gifts"),
    ("Can I give gifts to clients on behalf of the company?", ["prohibited"], "Gifts"),
    ("Who approves exceptions to the gifts policy?", ["CEO", "CHRO", "Group Ethics Officer"], "Gifts"),
    # Late-Food
    ("Can I get reimbursed for working late food?", ["8:00 pm", "Admin", "5:00 pm"], "Late-Food"),
    ("What is the trigger time for late dinner reimbursement?", ["8:00 pm"], "Late-Food"),
    ("How do I arrange food for working late at office?", ["Admin", "8:00 pm"], "Late-Food"),
    ("Who manages late working food arrangements?", ["Admin"], "Late-Food"),
    # Car-Expenses
    ("How do I claim fuel expenses for company car?", ["fuel vouchers", "petrol pumps"], "Car-Expenses"),
    ("How is company car maintenance handled?", ["dealerships", "company name"], "Car-Expenses"),
    ("Where do I get fuel for a company car?", ["fuel vouchers", "petrol pumps"], "Car-Expenses"),
    ("How are company car repair expenses handled?", ["dealerships", "company name"], "Car-Expenses"),
    # Admin-Purchases
    ("Can I buy stationery and claim reimbursement?", ["admin team", "no reimbursement"], "Admin-Purchases"),
    ("How are office supplies purchased at Arvind?", ["admin team"], "Admin-Purchases"),
    # Travel-Expenses
    ("Where should I claim telephone charges for international trips?", ["travel settlement"], "Travel-Expenses"),
    ("How do I claim excess baggage for international travel?", ["travel settlement"], "Travel-Expenses"),
    # Conveyance
    ("Where do I submit local conveyance expenses?", ["conveyance tab"], "Conveyance"),
    ("How are day-to-day conveyance expenses claimed?", ["conveyance tab"], "Conveyance"),
    # Submission
    ("Within how many days must I submit expense claims?", ["7 working days"], "Submission"),
    ("What is the deadline for submitting expense reimbursements?", ["7 working days"], "Submission"),
    # Non-Compliance
    ("What happens if I miss the expense submission deadline?", ["forfeiture of reimbursement"], "Non-Compliance"),
    ("What is the penalty for late expense submission?", ["forfeiture of reimbursement"], "Non-Compliance"),
    # Approval
    ("Who approves expense reimbursement requests?", ["Department Head", "Accounts Officer"], "Approval"),
    ("Who gives final approval for expense claims?", ["Department Head", "Accounts Officer"], "Approval"),
    # Exceptions
    ("Who approves exceptions to the expense policy?", ["CFO", "CHRO"], "Exceptions"),
    ("Can exceptions to expense policy be granted?", ["CFO", "CHRO"], "Exceptions"),
    # Puja
    ("Is puja expense reimbursed at Arvind?", ["Admin team", "Pandit"], "Puja"),
    ("How are religious ceremony expenses handled at Arvind?", ["Admin team", "Pandit"], "Puja"),
]

# ─────────────────────────────────────────────────────────────────────────────
# GROUP PERSONAL ACCIDENT INSURANCE SCHEME  (80 → 304)
# ─────────────────────────────────────────────────────────────────────────────
QUERIES_GPA = [
    # Basics / Policy-Details
    ("What is the Group Personal Accident Insurance Scheme?", ["accidental death", "disability"], "Policy-Details"),
    ("What is the policy number for GPA scheme?", ["ARV|COR|EBF_GPA"], "Policy-Details"),
    ("When is the GPA scheme effective?", ["01.01.2026"], "Policy-Details"),
    # Applicability
    ("Who is covered under Group Personal Accident Insurance?", ["management", "staff cadre"], "Applicability"),
    ("Does GPA cover all employees at Arvind?", ["management", "staff cadre"], "Applicability"),
    ("Are subsidiary employees covered under GPA?", ["subsidiaries"], "Applicability"),
    # Definitions
    ("What is TTD in personal accident insurance?", ["Temporary Total Disablement", "TTD"], "Definitions"),
    ("What is PTD in GPA?", ["Permanent Total Disablement", "PTD"], "Definitions"),
    ("What is PPD in accident insurance?", ["Permanent Partial Disablement", "PPD"], "Definitions"),
    ("What does CSI mean in GPA policy?", ["Capital Sum Insured", "CSI"], "Definitions"),
    ("What is the maximum Capital Sum Insured under GPA?", ["50 crores", "50,00,00,000"], "Maximum"),
    ("What is the maximum GPA cover at Arvind?", ["50 crores"], "Maximum"),
    # TTD
    ("What is the weekly TTD benefit?", ["5,000", "5000", "per week"], "TTD"),
    ("How many weeks does TTD benefit last?", ["100 weeks"], "TTD"),
    ("What is the maximum TTD payout?", ["100 weeks", "5,000"], "TTD"),
    ("What is Temporary Total Disablement benefit per week?", ["5,000 per week"], "TTD"),
    # Education-Grant
    ("What is the education grant for children under GPA?", ["10,000", "10000", "per child"], "Education-Grant"),
    ("How many children are covered for education grant in GPA?", ["2 children", "two children"], "Education-Grant"),
    ("What is the per-child education benefit in accident insurance?", ["10,000 per child"], "Education-Grant"),
    # CSI
    ("What is the Capital Sum Insured for accident insurance?", ["60 times", "monthly salary"], "CSI"),
    ("How is the Capital Sum Insured calculated in GPA?", ["60 times", "monthly salary"], "CSI"),
    # Fracture
    ("Are bone fractures covered under GPA?", ["fracture", "broken bones"], "Fracture"),
    ("What is the fracture cover in personal accident insurance?", ["broken bones", "fracture"], "Fracture"),
    ("Is there compensation for broken bones under GPA?", ["fracture cover", "broken bones"], "Fracture"),
    # Funeral
    ("Are funeral charges covered under GPA?", ["funeral charges"], "Funeral"),
    ("Does GPA cover body transportation costs?", ["carriage of dead body", "funeral charges"], "Funeral"),
    ("What is the funeral benefit in accident insurance?", ["funeral charges", "carriage of dead body"], "Funeral"),
    # Medical-Extension
    ("Does GPA have a medical expense extension?", ["medical extension", "hospitalization"], "Medical-Extension"),
    ("Are hospitalization costs covered under GPA?", ["medical extension"], "Medical-Extension"),
    # Death-Benefit
    ("What is the accidental death benefit under GPA?", ["accidental death", "60 times"], "Death-Benefit"),
    ("How much is paid on accidental death under GPA?", ["60 times monthly salary"], "Death-Benefit"),
    # Mid-Term
    ("Can GPA sum insured be changed during the year?", ["mid-term", "sum insured"], "Mid-Term"),
    ("What is the mid-term sum insured change process in GPA?", ["mid-term sum insured"], "Mid-Term"),
    # Ambulance
    ("Are ambulance charges covered under GPA?", ["ambulance"], "Ambulance"),
    ("Does personal accident insurance cover ambulance costs?", ["ambulance"], "Ambulance"),
    # Additional
    ("What does GPA stand for at Arvind?", ["Group Personal Accident", "accidental"], "Policy-Details"),
    ("Is natural death covered under GPA?", ["accidental death", "accidental"], "Policy-Details"),
    ("How is the GPA claim processed?", ["CMG", "Insurance Section"], "Policy-Details"),
]

# ─────────────────────────────────────────────────────────────────────────────
# GROUP TERM LIFE INSURANCE  (80 → 304)
# ─────────────────────────────────────────────────────────────────────────────
QUERIES_GTL = [
    # Basics
    ("What is Group Term Life Insurance at Arvind?", ["financial security", "natural death"], "Basics"),
    ("What does GTI cover?", ["natural death", "financial security"], "Basics"),
    ("Is GTI a death benefit policy?", ["natural death", "financial security"], "Basics"),
    ("What is GTL or GTI at Arvind?", ["Group Term Life", "natural death"], "Basics"),
    # Exclusions
    ("Is suicide covered under GTI?", ["suicide", "not be applicable"], "Exclusions"),
    ("What is not covered under Group Term Life Insurance?", ["suicide"], "Exclusions"),
    ("Does GTI pay out for self-inflicted death?", ["suicide", "not be applicable"], "Exclusions"),
    # Applicability
    ("Who is covered under Group Term Life Insurance?", ["management", "staff cadre", "subsidiary"], "Applicability"),
    ("Does GTI cover all Arvind employees?", ["management", "staff cadre"], "Applicability"),
    # Grade covers
    ("What is the life insurance cover for OT grade?", ["2,50,000"], "Grade-OT"),
    ("What is the GTI cover for E1 grade?", ["3,00,000"], "Grade-E1"),
    ("What is the GTI cover for E2 grade?", ["5,50,000"], "Grade-E2"),
    ("What is the life insurance for DET grade?", ["3,00,000"], "Grade-E1"),
    ("What is the GTI cover for M1 grade?", ["8,00,000"], "Grade-M1"),
    ("What is the life insurance cover for M2?", ["12,50,000"], "Grade-M2"),
    ("What is the GTI cover for M3?", ["18,00,000"], "Grade-M3"),
    ("What is the life insurance for BMH3?", ["30,00,000"], "Grade-BMH"),
    ("What is the GTI cover for BMH6?", ["30,00,000"], "Grade-BMH"),
    ("What is the life insurance cover for AVP?", ["50,00,000"], "Grade-AVP"),
    ("What is the GTI cover for VP grade?", ["85,00,000"], "Grade-VP"),
    ("What is the life insurance cover for BMH9?", ["1,00,00,000"], "Grade-BMH9"),
    # Settlement
    ("How is the death claim processed under GTI?", ["CMG", "death certificate", "Insurance Section"], "Settlement"),
    ("Who processes the GTI death claim?", ["CMG", "Insurance Section"], "Settlement"),
    ("What documents are needed for GTI death claim?", ["death certificate"], "Settlement"),
    ("What happens to GTI amount after employee death?", ["dues", "balance", "nominee", "Gratuity"], "Settlement"),
    ("How is GTI payout handled at Arvind?", ["CMG", "Insurance Section", "nominee"], "Settlement"),
    ("Who is the nominee under GTI?", ["nominee", "Gratuity"], "Settlement"),
    # Policy-Details
    ("What is the policy number for Group Term Life Insurance?", ["ARV|COR|EBF_GTI"], "Policy-Details"),
    ("What is the effective date of GTI policy?", ["01.01.2026"], "Policy-Details"),
    ("What is the GTI policy reference?", ["ARV|COR|EBF_GTI"], "Policy-Details"),
    ("When was GTI last updated?", ["01.01.2026"], "Policy-Details"),
    # Additional comparisons
    ("Which grade gets the highest life cover?", ["1,00,00,000", "BMH9"], "Grade-BMH9"),
    ("Which grade gets the lowest life cover?", ["2,50,000", "OT"], "Grade-OT"),
    ("What is the life insurance for M3H1 grade?", ["18,00,000"], "Grade-M3"),
    ("Does GTI cover accidental death?", ["natural death"], "Basics"),
    ("Is GTI a free benefit for employees?", ["financial security", "death"], "Basics"),
    ("Can I increase my GTI cover?", ["management", "staff cadre"], "Applicability"),
]

# ─────────────────────────────────────────────────────────────────────────────
# EXIT & FULL & FINAL SETTLEMENT POLICY  (92 → 304)
# ─────────────────────────────────────────────────────────────────────────────
QUERIES_FNF = [
    # Notice-Period
    ("What is the notice period at Arvind?", ["60", "sixty days"], "Notice-Period"),
    ("How many days notice is required for resignation?", ["60", "sixty"], "Notice-Period"),
    ("How long is the notice period for management staff?", ["60 days", "sixty"], "Notice-Period"),
    ("Can I resign with less than 60 days notice?", ["60", "sixty days", "notice pay"], "Notice-Period"),
    # Notice-Pay
    ("What is included in Notice Pay?", ["Basic Salary", "House Rent Allowance", "Flexible Benefits Plan"], "Notice-Pay"),
    ("How is Notice Pay calculated?", ["basic salary", "HRA", "Flexible Benefits Plan"], "Notice-Pay"),
    ("Does HRA form part of notice pay?", ["House Rent Allowance", "HRA"], "Notice-Pay"),
    ("What salary components make up notice pay?", ["Basic Salary", "HRA", "Flexible Benefits Plan"], "Notice-Pay"),
    # Resignation-Process
    ("How to resign from Arvind?", ["Darwinbox", "Employee Life Cycle", "Separation"], "Resignation-Process"),
    ("Can I resign by email at Arvind?", ["email", "not be considered valid"], "Resignation-Process"),
    ("When does my notice period start after resignation?", ["date", "resigned in the system"], "Resignation-Process"),
    ("Is email resignation valid at Arvind?", ["email", "not be considered valid"], "Resignation-Process"),
    ("What system is used to process resignation?", ["Darwinbox", "Employee Life Cycle"], "Resignation-Process"),
    ("How do I initiate resignation on Darwinbox?", ["Darwinbox", "Separation"], "Resignation-Process"),
    # FnF-Timeline
    ("What is the final settlement timeline?", ["30 days", "last working day"], "FnF-Timeline"),
    ("Within how many days is the final payout done?", ["30 days", "last working day"], "FnF-Timeline"),
    ("How long after my last working day will I get my FnF?", ["30 days"], "FnF-Timeline"),
    ("What is the FnF processing time at Arvind?", ["30 days", "last working day"], "FnF-Timeline"),
    # Eklavya
    ("What is the Eklavya policy recovery rule?", ["50%", "100%", "tuition"], "Eklavya"),
    ("What happens if I leave within 1 year of completing Eklavya?", ["100%", "tuition fee"], "Eklavya"),
    ("Eklavya tuition recovery if I leave within 2 years?", ["50%", "tuition fee"], "Eklavya"),
    ("If I leave after 2 years is Eklavya recovery waived?", ["50%", "tuition fee"], "Eklavya"),
    ("How is Eklavya training cost recovered on exit?", ["100%", "50%", "tuition fee"], "Eklavya"),
    # Letters
    ("When do I get the experience letter?", ["last working day"], "Letters"),
    ("When is the relieving letter issued?", ["No Dues Clearance"], "Letters"),
    ("Is the relieving letter given on the last working day?", ["No Dues Clearance", "last working day"], "Letters"),
    ("What is the experience letter issuance date?", ["last working day"], "Letters"),
    # No-Dues
    ("What is No Dues Clearance?", ["Business HR", "CMG", "IT", "Admin", "Finance"], "No-Dues"),
    ("Who is involved in No Dues Clearance?", ["Business HR", "CMG", "IT", "Admin", "Finance"], "No-Dues"),
    ("How do I complete No Dues during exit?", ["Business HR", "CMG", "IT"], "No-Dues"),
    # IT-Clearance
    ("What is IT clearance during exit?", ["laptops", "last working day", "damaged"], "IT-Clearance"),
    ("What do I need to return for IT clearance?", ["laptops", "last working day"], "IT-Clearance"),
    # PL-Payout
    ("How is PL balance paid during FnF?", ["Consolidated Salary", "Basic Salary"], "PL-Payout"),
    ("What is the PL encashment calculation for FnF?", ["Consolidated Salary", "Basic Salary"], "PL-Payout"),
    # PF
    ("Can I transfer my PF on exit?", ["transfer", "UAN", "EPFO"], "PF"),
    ("How is PF handled during full and final settlement?", ["UAN", "EPFO", "transfer"], "PF"),
    # Contact
    ("What is the HR contact for FnF queries?", ["corporate.hr@arvind.in"], "Contact"),
    ("Who do I email for FnF settlement exceptions?", ["corporate.hr@arvind.in"], "Contact"),
    # LWP
    ("What happens with LWP during notice period?", ["gross salary", "not adjusted"], "LWP"),
    ("Is LWP adjusted in the final settlement?", ["gross salary", "not adjusted"], "LWP"),
    # Policy-Details
    ("What is the policy number for FnF settlement?", ["ARV|COR|ELC_FnF"], "Policy-Details"),
    ("What is the effective date of exit policy?", ["24.02.2024"], "Policy-Details"),
]


# ─────────────────────────────────────────────────────────────────────────────
# WHISTLEBLOWER – additional cases for under-represented categories
# ─────────────────────────────────────────────────────────────────────────────
QUERIES_WB_EXTRA = [
    # Confidentiality (13 → 53)
    ("Is my identity protected if I report via the ethics helpline?", ["confidential", "identity"], "Confidentiality"),
    ("Will the company reveal who filed a whistleblower complaint?", ["confidential"], "Confidentiality"),
    ("What confidentiality protection exists for whistleblowers?", ["confidential"], "Confidentiality"),
    ("Can the respondent find out who made the complaint?", ["confidential", "identity"], "Confidentiality"),
    ("Is the whistleblower's identity kept secret throughout the investigation?", ["confidential"], "Confidentiality"),
    # Protection (13 → 53)
    ("What protection does a whistleblower have against retaliation?", ["adverse personnel action", "protected disclosure"], "Protection"),
    ("Can I be fired for filing a whistleblower complaint?", ["adverse personnel action"], "Protection"),
    ("Does the policy protect whistleblowers from demotion?", ["adverse personnel action"], "Protection"),
    ("What is the non-victimization clause in the whistleblower policy?", ["adverse personnel action", "victimization"], "Protection"),
    ("What happens to a manager who retaliates against a whistleblower?", ["adverse personnel action", "disciplinary"], "Protection"),
    # Retaliation-Recourse (13 → 53)
    ("What can I do if I face retaliation after whistleblowing?", ["adverse personnel action", "retaliation"], "Retaliation-Recourse"),
    ("Who do I approach if I'm victimized after filing a complaint?", ["Chairman", "committee"], "Retaliation-Recourse"),
    ("What recourse do I have if my manager takes adverse action after I report?", ["adverse personnel action"], "Retaliation-Recourse"),
    ("How does Arvind protect me from victimization after whistleblowing?", ["adverse personnel action"], "Retaliation-Recourse"),
    ("Can I escalate if I face career consequences for whistleblowing?", ["adverse personnel action", "Chairman"], "Retaliation-Recourse"),
    # False-Complaints (13 → 53)
    ("What happens if a whistleblower complaint is found to be false?", ["false", "malicious", "disciplinary"], "False-Complaints"),
    ("Can I be penalised for making a wrong whistleblower complaint?", ["malicious", "disciplinary"], "False-Complaints"),
    ("What is the consequence of a frivolous whistleblower complaint?", ["malicious", "disciplinary"], "False-Complaints"),
    ("Is there a penalty for filing a fake ethics complaint?", ["malicious", "disciplinary"], "False-Complaints"),
    ("What if I accidentally file an incorrect whistleblower complaint?", ["malicious", "disciplinary"], "False-Complaints"),
    # Reporting-Frequency (13 → 53)
    ("How often does the whistleblower committee report its findings?", ["quarterly", "quarterly report"], "Reporting-Frequency"),
    ("What is the reporting frequency for whistleblower cases?", ["quarterly"], "Reporting-Frequency"),
    ("How frequently is the ethics committee report shared?", ["quarterly report"], "Reporting-Frequency"),
    ("Does the whistleblower committee report annually or quarterly?", ["quarterly"], "Reporting-Frequency"),
    ("When is the whistleblower activity report submitted?", ["quarterly report"], "Reporting-Frequency"),
    # Investigation (13 → 53)
    ("Who investigates a whistleblower complaint?", ["independent", "investigation", "committee"], "Investigation"),
    ("What is the investigation process for whistleblower reports?", ["independent", "investigate"], "Investigation"),
    ("How long does a whistleblower investigation take?", ["investigate", "committee"], "Investigation"),
    ("Who conducts the investigation on ethics complaints?", ["independent", "investigation"], "Investigation"),
    ("What is the timeline for whistleblower investigation at Arvind?", ["investigate", "committee"], "Investigation"),
    # Follow-up (13 → 53)
    ("Can I follow up on my whistleblower complaint status?", ["follow up", "status"], "Follow-up"),
    ("How do I track my ethics complaint after submission?", ["follow up", "status"], "Follow-up"),
    ("Will I be informed of the outcome of my whistleblower complaint?", ["follow up", "informed"], "Follow-up"),
    ("What is the feedback mechanism for whistleblower reports?", ["follow up"], "Follow-up"),
    ("Does Arvind provide updates on whistleblower complaint progress?", ["follow up", "status"], "Follow-up"),
    # Responsibilities (13 → 53)
    ("Who is responsible for whistleblower policy implementation?", ["duty to cooperate", "committee"], "Responsibilities"),
    ("What are the responsibilities of managers under the whistleblower policy?", ["duty to cooperate"], "Responsibilities"),
    ("Is every employee required to cooperate in whistleblower investigations?", ["duty to cooperate"], "Responsibilities"),
    ("What is the duty to cooperate under the whistleblower policy?", ["duty to cooperate"], "Responsibilities"),
    ("What are the obligations of the whistleblower committee?", ["duty to cooperate", "committee"], "Responsibilities"),
    # Cross-Scope (43 → 83)
    ("Can I use whistleblower policy to report sexual harassment?", ["workplace harassment", "reportable"], "Cross-Scope"),
    ("What is the difference between whistleblower and POSH policy?", ["workplace harassment", "sexual harassment"], "Cross-Scope"),
    ("Can I report discrimination via the ethics helpline?", ["discrimination", "reportable"], "Cross-Scope"),
    ("Is financial fraud a reportable concern under whistleblower policy?", ["false invoicing", "procurement fraud", "bribery"], "Cross-Scope"),
    ("Can I report my manager for favouritism using whistleblower policy?", ["discrimination and favouritism", "reportable"], "Cross-Scope"),
]

# ─────────────────────────────────────────────────────────────────────────────
# POSH – additional cases for under-represented categories
# ─────────────────────────────────────────────────────────────────────────────
QUERIES_POSH_EXTRA = [
    # Scope (65 → 105)
    ("Does POSH cover same-sex harassment?", ["prohibits same-sex", "gender neutral"], "Scope"),
    ("Is POSH a gender-neutral policy?", ["gender neutral", "covers with equal rigour"], "Scope"),
    ("Does POSH protect male employees from harassment?", ["covers with equal rigour", "gender neutral"], "Scope"),
    ("What types of harassment are covered under POSH?", ["sexual harassment", "aggrieved woman"], "Scope"),
    ("Where does POSH apply — only office or also offsite events?", ["office parties", "workplace"], "Scope"),
    ("Does POSH cover harassment at office parties?", ["office parties"], "Scope"),
    ("Is harassment by a client covered under POSH?", ["third party", "external"], "Scope"),
    # Filing (39 → 79)
    ("How many copies of POSH complaint do I submit?", ["six copies"], "Filing"),
    ("What is the POSH complaint filing process?", ["six copies", "AIC"], "Filing"),
    ("Where do I submit a POSH complaint?", ["Supervisor", "Reporting Manager", "AIC"], "Filing"),
    ("Can I file a POSH complaint through my reporting manager?", ["Supervisor / Reporting Manager"], "Filing"),
    ("What is the deadline for filing a POSH complaint?", ["3 (three) months", "extended"], "Filing-Deadline"),
    ("Can the POSH filing deadline be extended?", ["extended for further 3 (three) months"], "Filing-Deadline"),
    # AIC-Composition (26 → 66)
    ("How many members are on the Arvind AIC?", ["2 members amongst employees", "minimum of 3"], "AIC-Composition"),
    ("Who chairs the AIC?", ["senior level woman employee", "Presiding Officer"], "AIC-Composition"),
    ("What percentage of AIC members must be women?", ["50% women", "50 percent women"], "AIC-Composition"),
    ("Who is the Presiding Officer of the AIC?", ["senior level woman employee", "Presiding Officer"], "AIC-Composition"),
    ("Is there an external member in the AIC?", ["external member", "legal practitioner"], "AIC-Composition"),
    ("How much is the external AIC member paid?", ["Rs. 250 per day", "250 per day"], "External-Member"),
    # AIC-Tenure (39 → 79)
    ("How long is an AIC member's term?", ["period of three years"], "AIC-Tenure"),
    ("Can AIC members be reappointed?", ["period of three years"], "AIC-Tenure"),
    ("When must an AIC vacancy be filled?", ["within 15 days"], "AIC-Vacancy"),
    # AIC-Powers (13 → 53)
    ("Does the AIC have the same powers as a civil court?", ["powers as that of a civil court"], "AIC-Powers"),
    ("What legal powers does the AIC have?", ["powers as that of a civil court", "civil court"], "AIC-Powers"),
    ("Can the AIC summon witnesses?", ["powers as that of a civil court"], "AIC-Powers"),
    ("Can the AIC call for documents?", ["powers as that of a civil court"], "AIC-Powers"),
    ("Does the AIC function like a court of law?", ["powers as that of a civil court"], "AIC-Powers"),
    # AIC-Procedures (13 → 53)
    ("How many days notice does AIC give before inquiry?", ["notice of 15 (fifteen) days"], "AIC-Procedures"),
    ("What is the AIC hearing notice period?", ["notice of 15 (fifteen) days"], "AIC-Procedures"),
    ("How much advance notice is given before POSH inquiry?", ["15 (fifteen) days"], "AIC-Procedures"),
    ("Can AIC inquiry proceed without proper notice?", ["notice of 15 (fifteen) days"], "AIC-Procedures"),
    # AIC-Report (13 → 53)
    ("Within how many days must AIC submit its report?", ["within a period of 10 (ten) days"], "AIC-Report"),
    ("What is the AIC report submission deadline?", ["10 (ten) days"], "AIC-Report"),
    ("How many days does the AIC get to file its findings?", ["10 (ten) days"], "AIC-Report"),
    # Interim-Relief (26 → 66)
    ("What interim leave can the aggrieved woman get during POSH inquiry?", ["3 (three) months", "leave to the Aggrieved Woman"], "Interim-Relief"),
    ("Can the aggrieved woman be transferred during POSH inquiry?", ["transfer", "interim relief"], "Interim-Relief"),
    ("What interim relief is available to POSH complainant?", ["leave to the Aggrieved Woman", "transfer"], "Interim-Relief"),
    # Interim-Action (13 → 53)
    ("Can the AIC suspend the respondent during POSH inquiry?", ["suspend the RE for defined period"], "Interim-Action"),
    ("What action can AIC take against respondent while inquiry is ongoing?", ["suspend the RE", "interim"], "Interim-Action"),
    ("Can the respondent be suspended before POSH inquiry is complete?", ["suspend the RE"], "Interim-Action"),
    # Anonymous (13 → 53)
    ("Can I file an anonymous POSH complaint?", ["Anonymous complaints will not be entertained"], "Anonymous"),
    ("Will Arvind accept anonymous sexual harassment complaints?", ["Anonymous complaints will not be entertained"], "Anonymous"),
    ("Can I report POSH without revealing my identity?", ["Anonymous complaints will not be entertained"], "Anonymous"),
    # Confidentiality (26 → 66)
    ("What happens if someone reveals details of a POSH case?", ["disciplinary action will be taken", "confidentiality"], "Confidentiality"),
    ("Is POSH inquiry information kept confidential?", ["confidential", "disciplinary action"], "Confidentiality"),
    # Legal-Representation (13 → 53)
    ("Can I bring a lawyer to AIC proceedings?", ["legal practitioner", "not be allowed"], "Legal-Representation"),
    ("Is legal representation allowed in POSH inquiry?", ["not be allowed", "legal practitioner"], "Legal-Representation"),
    ("Can the respondent hire a lawyer for AIC hearings?", ["legal practitioner", "not be allowed"], "Legal-Representation"),
    # Contact (39 → 79)
    ("What is the POSH helpline number?", ["18002008301", "1800 200 8301"], "Contact"),
    ("What is the POSH ethics helpline email?", ["arvind@ethicshelpline.in"], "Contact"),
    ("How can I reach the POSH committee?", ["18002008301", "arvind@ethicshelpline.in"], "Contact"),
    # False-Complaints (13 → 53)
    ("What happens if a POSH complaint is malicious?", ["allegation was malicious", "disciplinary"], "False-Complaints"),
    ("Can a false POSH complainant be punished?", ["malicious", "disciplinary action"], "False-Complaints"),
    ("What action is taken against a malicious POSH complaint?", ["allegation was malicious"], "False-Complaints"),
    # Applicability (26 → 66)
    ("Are all Arvind employees covered under POSH?", ["All persons employed at Arvind"], "Applicability"),
    ("Does POSH apply to contract workers?", ["All persons employed at Arvind"], "Applicability"),
    ("Is POSH applicable to visiting consultants?", ["All persons employed at Arvind"], "Applicability"),
]


# ─────────────────────────────────────────────────────────────────────────────
# GENERATE ALL SUITES
# ─────────────────────────────────────────────────────────────────────────────

def generate_expanded_small():
    suite = []
    suite += make_cases(QUERIES_VDCS,  "Voluntary Death Contribution Scheme")
    suite += make_cases(QUERIES_LCP,   "Local Conveyance Policy")
    suite += make_cases(QUERIES_DTSP,  "Domestic Travel Expense Settlement Procedure")
    suite += make_cases(QUERIES_PANKH, "Pankh Employee Referral")
    suite += make_cases(QUERIES_EER,   "Employee Expense Reimbursement Policy")
    suite += make_cases(QUERIES_GPA,   "Group Personal Accident Insurance Scheme")
    suite += make_cases(QUERIES_GTL,   "Group Term Life Insurance")
    suite += make_cases(QUERIES_FNF,   "Exit & Full & Final Settlement Policy")
    return suite

def generate_whistleblower_balanced():
    return make_cases(QUERIES_WB_EXTRA, "Whistleblower Policy")

def generate_posh_balanced():
    return make_cases(QUERIES_POSH_EXTRA, "POSH Policy (Prevention of Sexual Harassment)")


if __name__ == "__main__":
    small = generate_expanded_small()
    wb    = generate_whistleblower_balanced()
    posh  = generate_posh_balanced()

    with open("/home/user/ARVIN/expanded_small_policies_suite.json", "w") as f:
        json.dump(small, f, indent=2)
    with open("/home/user/ARVIN/whistleblower_balanced_suite.json", "w") as f:
        json.dump(wb, f, indent=2)
    with open("/home/user/ARVIN/posh_balanced_suite.json", "w") as f:
        json.dump(posh, f, indent=2)

    # summary
    from collections import Counter, defaultdict
    print("=== Generated suites ===\n")
    for label, suite in [("Small Policies (expanded)", small), ("Whistleblower (balanced)", wb), ("POSH (balanced)", posh)]:
        by_pol = Counter(c["source"] for c in suite)
        print(f"{label}: {len(suite)} total cases")
        for pol, n in sorted(by_pol.items()):
            print(f"  {pol}: {n}")
        print()
